# Generated by Django 4.2.7 on 2024-03-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jee_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NUMERICAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXC', models.CharField(max_length=50)),
                ('SUB', models.TextField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], null=True)),
                ('QNN', models.TextField(blank=True, choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], null=True)),
                ('QA', models.FloatField()),
            ],
        ),
    ]
